### ISSUE TITLE
error during ps script analyzer run

### ISSUE THREAD

**Issue by Sarothur** [gretard/sonar-ps-plugin#21]
Hi we have a following issue while script analyzer is working:

##[error]Invoke-ScriptAnalyzer : The following exception occurred while constructing the attribute "ProjectValidateAttribute": 
##[error]"Value cannot be null.
Parameter name: key"
+ FullyQualifiedErrorId : RULE_ERROR,Microsoft.Windows.PowerShell.ScriptAnalyzer.Commands.InvokeScriptAnalyzerComm 

I think it was something about ps script analyzer version, but even update did not help.
Is it possible that there is some typo or issue in custom ps script analyzer rules? I was investigating the code from this repo and everything seems to be fine here.
The werid thing is that it was working without issue for whole year now it pops this error.
But after this weird error it analyses everything and send results to sonarqube.

Any suggestions how to get rid of this error?

**Comment by gretard** [comment]
Hi @Sarothur ,

Is this issue still relevant?
