### ISSUE TITLE
Getting the plugin to work

### ISSUE THREAD

**Issue by huntantr** [gretard/sonar-ps-plugin#31]
Have this installed in SonarQube , plus have the PSScriptAnalyzer on the build machine. I know this works as I run it manually. How do I get SonarQube to do the scanning and create issues?

**Comment by henry-1** [comment]
I wrote a short description how I integrated this plugin in SonarQube
https://github.com/henry-1/ScriptAnalyzer_CustomRules/blob/main/readme.md

**Comment by gretard** [comment]
Hi @huntantr ,

Did you manage to get everything working?
