### ISSUE TITLE
PS Plugin Support for Linux?

### ISSUE THREAD

**Issue by kirkpabk** [gretard/sonar-ps-plugin#32]
Since PowerShell is largely cross-platform, are there any plans to help drive PS Script Analyzer for Linux?

Understand this is not core to this project--but additional pushing, might help.

**Comment by gretard** [comment]
Hi,
Thanks for raising this, but I think it is already supported. Please check:

1. Installing Powershell on Linux (for example Ubuntu https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4)
2. Installing PSScript analyzer (https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/overview?view=ps-modules#installing-psscriptanalyzer), for example in the terminal execute to install it:
`pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"`
3. Test if module is working properly:
`pwsh -Command "Invoke-ScriptAnalyzer -ScriptDefinition '"b" = "b"; function eliminate-file () { }'"`
4. Once you executed previous steps, please specify "sonar.ps.executable" property to point to powershell executable on the linux (you can find it by using command `whereis pwsh`):
`sonar.ps.executable="/usr/bin/pwsh"`

Now plugin should be able to work on Linux and you should see results on the SonarQube server :) Please let me know if that helped.

**Comment by kirkpabk** [comment]
Thanks @gretard!  We will give it a shot.  Our environment is closed, so we'd have the manually install the modules.  The only binaries we saw were the packaged ones with the .dll assemblies.  So--we'll take another look.   Thanks again!
