### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by diegoibellini** [gretard/sonar-ps-plugin#6]
Hi @gretard 

We're trying to import the Code Coverage of the Pester output test to the SonarQube dashboard. Do you have some experience to do it ? Or Do you know how we can do it ? 

Best!
DIB

**Comment by exologica** [comment]
Hi @gretard, thank you so much!

I'm working with @diegoibellini around that. We create a parser that take the pester jococo output and make a generic test based on sonarqube documentation.

We see the pester -codecoverage parameter percent value in sonarqube right now that correlate with the "INSTRUCTION" output.

Ex:
```sh
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.0//EN" "report.dtd">
<report name="Pester (01/09/2019 14:15:29)">
<sessioninfo id="this" start="1547043329214" dump="1547043329328" />
<counter type="INSTRUCTION" missed="50" covered="100" />
<counter type="LINE" missed="2" covered="3" />
<counter type="METHOD" missed="0" covered="2" />
<counter type="CLASS" missed="0" covered="1" />
</report>
```

The question now it's what we can do with all the rest of the counters, LINE, METHOD, CLASS ?

Also it seems that if we make a batch test with a lot of powershell scripts in the same folder, we have the same single output in just one "TestsCoverage.Jacoco.xml" file. It's that ok?

Invoke-Pester .\tests\* -CodeCoverage .\src\* -OutputFile TestResults.NUnitXml.xml -OutputFormat NUnitXml -CodeCoverageOutputFile TestsCoverage.Jacoco.xml

**Comment by gretard** [comment]
Hi,

I am very glad that you found the plugin useful. With regards to @exologica issue - I will need to double check that, but I think if report contains all information - then it is ok to have same file. And with regards to counters in general - unless you extract line by line information (for example, line1 - covered: true, line2 - covered: false and so on) and transform that to the Generic format - then you can do something.

And with regards to @diegoibellini issue - I would suggest looking into (Generic Issue Format)[https://docs.sonarqube.org/latest/analysis/generic-issue/]. You could run you custom tools and report custom issues by setting sonar.externalIssuesReportPaths setting :)  In addition to this, you could try writing custom tools by using AST. You can find out more at https://blog.ipswitch.com/how-to-take-advantage-of-powershells-abstract-syntax-tree.
