### ISSUE TITLE
Script-Analyzer Powershell process hangs

### ISSUE THREAD

**Issue by moerketh** [gretard/sonar-ps-plugin#9]
## Description
The Script-Analyzer Powershell process does not complete when there is a significant amount of Script-Analyzer process output. The Script-Analyzer process that this sensor is failing on has about 500 lines of output. This is larger then other builds where this sensor does work.

This seems to be caused by the process output never being read in the ScriptAnalyzerSensor. Also see: https://stackoverflow.com/a/5483976

## Steps to reproduce
Run the ScriptAnalyzerSensor on a set of files that create several hundreds of lines of output (both standard output and error output). I have not tested where the actual limit is, 500 seems to be enough on my environment (see below).

## Expected behavior
Powershell analysis is executed and completes in about 7 minutes.

## Actual behavior
Powershell analysis is started, but never completes until the builds times out after 60 minutes.

## Diagnostic logs
2019-02-07T10:27:08.9714256Z INFO: Sensor ScriptAnalyzerSensor [ps]
2019-02-07T10:27:08.9991575Z INFO: Starting running powershell analysis: D:\4\_work\3\s\.scannerwork\.sonartmp\ps387899190958008789scriptAnalyzer.ps1 -inputDir D:\4\_work\3\s -output D:\4\_work\3\s\.scannerwork\.sonartmp\2744577610841829641.tmp
..hangs..

## Environment
OS: Windows 2016 v1607
Packages and versions:
PowerShell	5.1.14393.2636
java	C:\Program Files\Java\jre1.8.0_161
java_8_x64	C:\Program Files\Java\jre1.8.0_161
PSScriptAnalyzer	1.17.1

**Comment by gretard** [comment]
Thank you so much for this :)  Will include merged PR in the next release :)
